// This file is generated by compile-translations.js script
// prettier-ignore
module.exports = [
  {
    "languageCode": "pseudo_LOCALE",
    "languageName": "for development only",
    "languageNativeName": "Pseudolocalization",
    "translationRatio": 0.997872340425532
  }
];
